<?php

/**
 * @author Noel Antonio
 * @date 01-28-2014
 */
$this->breadcrumbs = array(
    'Activation Code Management'
);

$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'index-form',
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),        
    'htmlOptions'=>array('class'=>'well'),
));

echo CHtml::link('GENERATE NEW CODES', Yii::app()->createUrl('activationCode/create'));

$this->widget('zii.widgets.grid.CGridView', array(
        'dataProvider' => $dataProvider,
        'enablePagination' => true,
        'columns' => array(
                        array('name'=>'ActivationCodeBatchID',
                            'header'=>'Batch ID',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["activation_code_batch_id"])',
                            'htmlOptions' => array('style' => 'text-align:center; width: 5%'),    
                        ),
                        array('name'=>'GeneratedBy',
                            'header'=>'Generated By',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["member_name"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'DateGenerated',
                            'header'=>'Date Generated',
                            'type'=>'raw',
                            'value'=>'CHtml::encode(date("Y-M-d h:i:s a", strtotime($data["date_generated"])))',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'IPAddress',
                            'header'=>'IP Address',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["generated_from_ip"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'Quantity',
                            'header'=>'Quantity',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["batch_quantity"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'ActiveCodes',
                            'header'=>'Active Codes',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["batch_quantity"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'UsedCodes',
                            'header'=>'Used Codes',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["batch_quantity"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'Percentage',
                            'header'=>'Percentage',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["batch_quantity"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'Action',
                            'header'=>'Action',
                            'type'=>'raw',
                            'value'=>'CHtml::link("View Codes", array("activationCode/codes", "id"=>$data["activation_code_batch_id"]))',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
        )
        ));

$this->endWidget();
?>