<?php

/**
 * @author Noel Antonio
 * @date 01-28-2014
 */
$this->breadcrumbs = array(
    'Activation Code Generation History'
);
?>
<h1>Activation Code Generation History</h1>

<?php
$form = $this->beginWidget('CActiveForm', array(
        'id' => 'history-form',
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),        
    ));

$this->widget('zii.widgets.grid.CGridView', array(
        'dataProvider' => $dataProvider,
        'enablePagination' => true,
        'columns' => array(
                        array('name'=>'ActivationCodeBatchID',
                            'header'=>'Activation Code Batch ID',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["activation_code_batch_id"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ), 
                        array('name'=>'Quantity',
                            'header'=>'Quantity',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["batch_quantity"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'GeneratedBy',
                            'header'=>'Generated By',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["member_name"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'DateGenerated',
                            'header'=>'Date Generated',
                            'type'=>'raw',
                            'value'=>'CHtml::encode(date("Y-M-d h:i:s a", strtotime($data["date_generated"])))',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'IPAddress',
                            'header'=>'IP Address',
                            'type'=>'raw',
                            'value'=>'CHtml::encode($data["generated_from_ip"])',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
                        array('name'=>'Action',
                            'header'=>'Action',
                            'type'=>'raw',
                            'value'=>'CHtml::link("View Codes", array("activationCode/codes", "id"=>$data["activation_code_batch_id"]))',
                            'htmlOptions' => array('style' => 'text-align:center'),    
                        ),
        )
        ));

?>

<?php $this->endWidget(); ?>